### ISSUE TITLE
Escolher uma tecnologia para o nosso projeto

### ISSUE THREAD

**Issue by MarcusMann** [pacotei/devlist-html#1]
- Python ( Flask )
- Nodejs ( Express )
- Adonisjs

**Comment by SuperFeliz** [comment]
Backend => Python
Frontend => Vue

**Comment by seoimg** [comment]
Backend => Python
Frontend => Vue

**Comment by fbrump** [comment]
```json
{
    "Backend": "Python (Flask) or (FastApi)",
    "Frontend":"Vue",
    "CSS":"Bulma",
    "Container": "Docker/docker-compose"
}
```

**Comment by Riverfount** [comment]
Backend em Python (Flask ou FastApi)
Frontend: VueJS

**Comment by Pbezerra-dev** [comment]
Backend == Python
Frontend == Vuejs

**Comment by MarcusMann** [comment]
> ```json
> {
>     "Backend": "Python (Flask) or (FastApi)",
>     "Frontend":"Vue",
>     "CSS":"Bulma",
>     "Container": "Docker/docker-compose"
> }
> ```

Nós já estamos usando papercss
https://www.getpapercss.com/

**Comment by fbrump** [comment]
> > ```json
> > {
> >     "Backend": "Python (Flask) or (FastApi)",
> >     "Frontend":"Vue",
> >     "CSS":"Bulma",
> >     "Container": "Docker/docker-compose"
> > }
> > ```
> 
> Nós já estamos usando papercss
> https://www.getpapercss.com/

Então fico com isso:
 ```json
{
   "Backend": "Python (Flask) or (FastApi)",
    "Frontend":"Vue",
    "Container": "Docker/docker-compose"
 }
